theme: jekyll-theme-hacker
title: Systemic Lymphoid Architecture Response Assessment (SYLARAS)
description: A computational tool for discovery-based immunophenotyping
# Supervised exploration and tidy graphical display of single-cell data

sass:
    load_paths:
        - _scss
        - node_modules

plugins:
    - jekyll-redirect-from
exclude: []

google_analytics: UA-119988389-2
