theme: jekyll-theme-hacker
title: Systemicll Lymphoid Architecture Response Assessment (SYLARAS)
description: Supervised exploration and tidy display of discovery-based immunophenotyping data
featured-img: /assets/img/fig0.png

sass:
    load_paths:
        - _scss
        - node_modules
plugins:
    - jekyll-redirect-from
exclude: []

google_analytics: UA-119988389-2
