theme: jekyll-theme-hacker
title: Systemic Lymphoid Architecture Response Assessment (SYLARAS)
description: Supervised exploration and tidy visualization of discovery-based immunophenotyping data

sass:
    load_paths:
        - _scss
        - node_modules
plugins:
    - jekyll-redirect-from
exclude: []
